export { default as fsa } from "./fsa.png"
export { default as awwr } from "./awwr.png"
export { default as ec } from "./ec.png"
export { default as more } from "./more.png"
export { default as tsp } from "./tsp.png"
export { default as rdts } from "./rdts.png"
export { default as rd } from "./rd.png"
