export { default as Navbar } from './Navbar'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as SignUp } from './Signup'
export { default as Form } from './Form'
export { default as Modal } from './Modal'
export { default as Alerts } from './Alerts'
export {default as Card} from  './Card'
export {default as Explore} from  './Explore'
export {default as Footer} from  './Footer'
// export {default as Favorites} from  './favorites'
